// https://docusaurus.io/docs/sidebar

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cv: [
    {
      type: "autogenerated",
      dirName: "cv",
    },
  ],
};

export default sidebars; //module.exports = sidebars;
