// https://docusaurus.io/docs/sidebar

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  resume: [
    {
      type: "autogenerated",
      dirName: "resume",
    },
  ],
  support: [
    {
      type: "autogenerated",
      dirName: "support",
    },
  ],
};

module.exports = sidebars;
